# Generated by Django 5.1 on 2025-04-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='watch_collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_image', models.ImageField(blank=True, null=True, upload_to='core/watch_collection')),
                ('watch_name', models.CharField(max_length=200)),
                ('watch_price', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'watch_collection',
                'verbose_name_plural': 'watches_collection',
            },
        ),
        migrations.AlterField(
            model_name='watch',
            name='watch_price',
            field=models.CharField(max_length=20),
        ),
    ]
