# Generated by Django 5.1.7 on 2025-04-15 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_watch_collection_alter_watch_watch_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='watch_collection',
            new_name='watchCollection',
        ),
    ]
