# Generated by Django 5.1.7 on 2025-04-15 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_watch_collection_watchcollection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='watchCollection',
            new_name='rolex_collection',
        ),
        migrations.AlterModelOptions(
            name='rolex_collection',
            options={'verbose_name': 'rolex_collection', 'verbose_name_plural': 'rolex_collection'},
        ),
    ]
