# Generated by Django 5.1.7 on 2025-04-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_watchcollection_rolex_collection_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rolex_collection',
            old_name='watch_name',
            new_name='rolex_name',
        ),
        migrations.RenameField(
            model_name='rolex_collection',
            old_name='watch_price',
            new_name='rolex_price',
        ),
        migrations.RemoveField(
            model_name='rolex_collection',
            name='watch_image',
        ),
        migrations.AddField(
            model_name='rolex_collection',
            name='rolex_image',
            field=models.ImageField(blank=True, null=True, upload_to='core/rolex_collection'),
        ),
    ]
