# Generated by Django 5.1.7 on 2025-04-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_watch_name_rolex_collection_rolex_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='hublot_collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hublot_image', models.ImageField(blank=True, null=True, upload_to='core/hublot_collection')),
                ('hublot_name', models.CharField(max_length=200)),
                ('hublot_price', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'hublot_collection',
                'verbose_name_plural': 'hublot_collection',
            },
        ),
    ]
