# Generated by Django 5.1.7 on 2025-04-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_hublot_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolex_collection',
            name='rolex_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
