# Generated by Django 5.1.7 on 2025-04-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rolex_collection_rolex_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='hublot_collection',
            name='hublot_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
