# Generated by Django 5.1.7 on 2025-04-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_hublot_collection_hublot_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hublot_collection',
            name='hublot_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='rolex_collection',
            name='rolex_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
