# Generated by Django 5.1 on 2025-04-14 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watch',
            options={'verbose_name': 'Watch', 'verbose_name_plural': 'product_Watches'},
        ),
    ]
