# Generated by Django 5.1.7 on 2025-04-15 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_watch_watches'),
    ]

    operations = [
        migrations.CreateModel(
            name='watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_image_1', models.ImageField(blank=True, null=True, upload_to='product/watch')),
                ('watch_name', models.CharField(max_length=50)),
                ('watch_desc', models.CharField(max_length=1000)),
                ('watch_full_name', models.CharField(max_length=100)),
                ('watch_model_case', models.CharField(max_length=50)),
                ('watch_material', models.CharField(max_length=50)),
                ('watch_price', models.CharField(max_length=30)),
                ('watch_reference', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Watch',
                'verbose_name_plural': 'products_Watches',
            },
        ),
    ]
