# Generated by Django 5.1.7 on 2025-04-15 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_watch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='watches',
        ),
    ]
