# Generated by Django 5.1.7 on 2025-04-15 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_delete_watches'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watch',
            options={'verbose_name': 'Watch', 'verbose_name_plural': 'Rolex_Watches'},
        ),
    ]
