# Generated by Django 5.1.7 on 2025-04-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_watch_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='hublot_watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hublot_watch_image_1', models.ImageField(blank=True, null=True, upload_to='product/watch')),
                ('hublot_watch_name', models.CharField(max_length=50)),
                ('hublot_watch_desc', models.CharField(max_length=1000)),
                ('hublot_watch_full_name', models.CharField(max_length=100)),
                ('hublot_watch_model_case', models.CharField(max_length=50)),
                ('hublot_watch_material', models.CharField(max_length=50)),
                ('hublot_watch_price', models.CharField(max_length=30)),
                ('hublot_watch_reference', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'hublot_Watch',
                'verbose_name_plural': 'hublot_Watches',
            },
        ),
        migrations.CreateModel(
            name='Rolex_watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rolex_watch_image_1', models.ImageField(blank=True, null=True, upload_to='product/watch')),
                ('Rolex_watch_name', models.CharField(max_length=50)),
                ('Rolex_watch_desc', models.CharField(max_length=1000)),
                ('Rolex_watch_full_name', models.CharField(max_length=100)),
                ('Rolex_watch_model_case', models.CharField(max_length=50)),
                ('Rolex_watch_material', models.CharField(max_length=50)),
                ('Rolex_watch_price', models.CharField(max_length=30)),
                ('Rolex_watch_reference', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Rolex_Watch',
                'verbose_name_plural': 'Rolex_Watches',
            },
        ),
        migrations.DeleteModel(
            name='watch',
        ),
    ]
