# Generated by Django 5.1 on 2025-04-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_hublot_watch_rolex_watch_delete_watch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hublot_watch',
            name='hublot_watch_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='product/hublot/watch'),
        ),
        migrations.AlterField(
            model_name='rolex_watch',
            name='Rolex_watch_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='product/rolex/watch'),
        ),
    ]
