# Generated by Django 5.1.7 on 2025-04-18 08:39

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_hublot_watch_hublot_watch_image_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_image_1', models.ImageField(blank=True, null=True, upload_to=products.models.image_upload_path)),
                ('watch_name', models.CharField(max_length=50)),
                ('watch_full_name', models.CharField(max_length=100)),
                ('watch_model_case', models.CharField(max_length=50)),
                ('watch_material', models.CharField(max_length=50)),
                ('watch_price', models.CharField(max_length=30)),
                ('watch_reference_no', models.CharField(max_length=50)),
                ('watch_brand', models.CharField(choices=[('Rolex', 'Rolex'), ('Hublot', 'Hublot')], max_length=50)),
            ],
            options={
                'verbose_name': 'Watch_product',
                'verbose_name_plural': 'Watch_list',
            },
        ),
        migrations.DeleteModel(
            name='hublot_watch',
        ),
        migrations.DeleteModel(
            name='Rolex_watch',
        ),
    ]
