# Generated by Django 5.1.7 on 2025-04-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_watch_delete_hublot_watch_delete_rolex_watch'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='watch_desc',
            field=models.TextField(default='Best watch'),
        ),
    ]
