# Generated by Django 5.1.7 on 2025-04-18 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_watch_watch_desc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='watch',
            new_name='product_watch',
        ),
    ]
