# Generated by Django 5.1.7 on 2025-04-18 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_rename_watch_product_watch'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product_watch',
            new_name='watch_collection',
        ),
    ]
