# Generated by Django 5.1.7 on 2025-04-19 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_rename_product_watch_watch_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch_collection',
            name='watch_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
