# Generated by Django 5.1.7 on 2025-04-19 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_all_watch_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ALL_WATCH_LIST',
        ),
    ]
