# Generated by Django 5.1.7 on 2025-04-19 06:26

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_delete_all_watch_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='ALL_WATCH_LIST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_image_1', models.ImageField(blank=True, null=True, upload_to=products.models.image_upload_path)),
                ('watch_name', models.CharField(max_length=50)),
                ('watch_desc', models.TextField(default='Best watch')),
                ('watch_full_name', models.CharField(max_length=100)),
                ('watch_model_case', models.CharField(max_length=50)),
                ('watch_material', models.CharField(max_length=50)),
                ('watch_price', models.CharField(max_length=30)),
                ('watch_reference_no', models.CharField(max_length=50)),
                ('watch_brand', models.CharField(choices=[('Rolex', 'Rolex'), ('Hublot', 'Hublot')], max_length=50)),
                ('watch_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Watch_product',
                'verbose_name_plural': 'ALL_Watch_list',
            },
        ),
    ]
