# Generated by Django 5.1.7 on 2025-04-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_delete_all_watch_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch_collection',
            name='watch_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
